dist: bionic

language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO=""   # no django
  - DJANGO="Django>=1.8,<1.9"


before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get remove openjdk-11-jdk
  - sudo apt-get install openjdk-8-jdk
  - sudo mkdir /opt/eulfedora_ci
  - sudo chmod 777 /opt/eulfedora_ci
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

install:
  - ci/setup-fedora.sh
  - pip install --upgrade pip setuptools
  - pip install coveralls $DJANGO
  - pip install -e .
  - pip install -e ".[test]"
  - cp ci/testsettings.py test/localsettings.py

before_script:
  - ci/start-fedora.sh

script:
  nosetests test --with-coverage --cover-package=eulfedora --cover-xml --with-xunit

after_success:
  - coveralls
